"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR / 'data'
DATA_DIR.mkdir(parents=True, exist_ok=True)

PAYMENTS_LOG_FILE = DATA_DIR / 'payments_audit.log'
CLEANUPS_LOG_FILE = DATA_DIR / 'cleanups_audit.log'


env = environ.Env(
    DEBUG=(bool, False),
    DEBUG_FRAGMENT=(bool, False),
    DEBUG_PLATEGA=(bool, False),
    DEBUG_PAYPEAR=(bool, False),
    USE_SSL=(bool, True),
    ALLOWED_HOSTS=(list, []),
    PAYPEAR_WEBHOOK_IPS=(list, ['158.160.85.101']),
    CELERY_BROKER_URL=(str, 'redis://localhost:6379/0'),
    NOTIFY_ABOUT_ORDERS=(bool, True),
    SUPPORT_URL=(str, 'https://google.com/'),
    FEEDBACK_URL=(str, 'https://google.com/')
)

environ.Env.read_env(BASE_DIR / '.env')

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
DEBUG_FRAGMENT=env('DEBUG_FRAGMENT')
DEBUG_PLATEGA=env('DEBUG_PLATEGA')
DEBUG_PAYPEAR=env('DEBUG_PAYPEAR')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
SITE_DOMAIN = env('SITE_DOMAIN')
FRAGMENT_WEBHOOK_SECRET = env('FRAGMENT_WEBHOOK_SECRET')

CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN')
ADMIN_CHAT_ID = env('ADMIN_CHAT_ID', cast=int)
ADMIN_BROADCAST_TOPIC_ID = env('ADMIN_BROADCAST_TOPIC_ID', cast=int)
ADMIN_ORDERS_TOPIC_ID = env('ADMIN_ORDERS_TOPIC_ID', cast=int)
NOTIFY_ABOUT_ORDERS = env('NOTIFY_ABOUT_ORDERS')
CHANNEL_ID = env('CHANNEL_ID', cast=int)
CHANNEL_LINK = env('CHANNEL_LINK')

SUPPORT_URL = env('SUPPORT_URL')
FEEDBACK_URL = env('FEEDBACK_URL')

FRAGMENT_API_URL = env('FRAGMENT_API_URL')
FRAGMENT_CURRENCY = env('FRAGMENT_CURRENCY')
FRAGMENT_POLL_SECONDS = env.int('FRAGMENT_POLL_SECONDS', default=15)
FRAGMENT_POLL_MAX_AGE_HOURS = env.int('FRAGMENT_POLL_MAX_AGE_HOURS', default=24)
FRAGMENT_POLL_DOUBT_AFTER_MINUTES = env.int('FRAGMENT_POLL_DOUBT_AFTER_MINUTES', default=30)

PLATEGA_API_URL = env('PLATEGA_API_URL')
PLATEGA_MERCHANT_ID = env('PLATEGA_MERCHANT_ID')
PLATEGA_SECRET = env('PLATEGA_SECRET')

PAYPEAR_API_URL = env('PAYPEAR_API_URL')
PAYPEAR_SHOP_ID = env('PAYPEAR_SHOP_ID')
PAYPEAR_SECRET = env('PAYPEAR_SECRET')
PAYPEAR_WEBHOOK_IPS = env.list('PAYPEAR_WEBHOOK_IPS')
PAYPEAR_USE_WEBHOOK = env.bool('PAYPEAR_USE_WEBHOOK', default=True)
PAYPEAR_POLL_SECONDS = env.int('PAYPEAR_POLL_SECONDS', default=5)

USE_SSL = env('USE_SSL')

if USE_SSL:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True


import django_stubs_ext
django_stubs_ext.monkeypatch()


# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'skip_not_found': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record, d=DEBUG: d or ('Not Found:' not in record.getMessage()),
        },
    },
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {message}', 'style': '{'},
        'audit_format': {'format': '{levelname} - {asctime} - {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'django_console': {'class': 'logging.StreamHandler', 'formatter': 'verbose', 'filters': ['skip_not_found']},
        'payments_file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': str(PAYMENTS_LOG_FILE), 'formatter': 'audit_format'},
        'cleanups_file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': str(CLEANUPS_LOG_FILE), 'formatter': 'audit_format'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['django_console'], 'level': 'INFO', 'propagate': False},
        'httpx': {'handlers': ['console'], 'level': 'WARNING'},
        'payment_audit': {'handlers': ['payments_file'], 'level': 'INFO', 'propagate': False},
        'cleanup_audit': {'handlers': ['cleanups_file'], 'level': 'INFO', 'propagate': False},
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'solo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
            'init_command': (
                f'PRAGMA journal_mode=WAL;'
                f'PRAGMA synchronous=NORMAL;'
                f'PRAGMA cache_size=-20000;'
                f'PRAGMA foreign_keys=ON;'
                f'PRAGMA temp_store=FILE;'
            ),
        }
    }
}


# Storages

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'


# URL, по которому медиафайлы будут доступны в браузере
MEDIA_URL = '/media/'

# Физический путь на сервере, куда Django будет сохранять файлы
MEDIA_ROOT = BASE_DIR / 'data' / 'media'
